default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password1
  socket: /var/run/mysqld/mysqld.sock


development:
  <<: *default
  database: ember-crm_development


production:
  <<: *default
  database: ember-crm_production
  username: ember-crm
  password: <%= ENV['EMBER-CRM_DATABASE_PASSWORD'] %>
